<?php

function islandora_utils_plugin_validate_object_schema() {
  $schema = array();

  $schema['islandora_utils_plugin_validate_object_content_models'] = array(
    'description' => 'stores content models and datastreams to validate against',
    'fields' => array(
      'content_model_id' => array(
        'description' => 'The ID of the record',
        'type' => 'serial',
        'length' => 11,
        'not null' => TRUE,
      ),
      'content_model_name' => array(
        'description' => 'The name of content model.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ),
      'content_model_datastreams' => array(
        'description' => 'The space seperated datastreams to check for',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('content_model_id'),
  );

  return $schema;
}
