<?php

function islandora_utils_plugin_validate_object_islandora_utils_plugin() {
  return array(
    'validate' => array (
      'title' => 'Validate Objects',
      'module' => 'islandora_utils_plugin_validate_object',
      'file' => 'ValidateObjectPlugin.inc',
      'class' => 'ValidateObjectPlugin',
      'function' => "process",
      'description' => 'Validate objects against content model requirements. Eg: missing datastreams or empty datastreams',
      'what' => 'else?'
    ),
  );
}


function islandora_utils_plugin_validate_object_form_alter(&$form, &$form_state, $form_id) {
  dsm($form_state, 'form state');
  switch ($form_id) {
    case 'islandora_utils_settings_form':
    //case 'islandora_utils_form':

      $form['islandora_utils_plugin_options']['islandora_utils_validate_object_settings'] = array(
        '#type' => 'fieldset',
        '#title' => t('Validate object settings'),
        '#description' => t("Settings for validating objects and datastreams"),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        );

      if(isset($form_state['triggering_element'])) {
        if($form_state['triggering_element']['#button_id'] == 'islandora-utils-settings-validate-add-content-model') {
          unset($form_state['triggering_element']['#button_id']);
          $content_model = $form_state['values']['islandora_utils_validate_object_settings_content_models_name'];
          $dsids_raw = $form_state['values']['islandora_utils_validate_object_settings_content_models_ds'];
          dsm('fire twice');
          if(!empty($content_model) && !empty($dsids_raw)) {

            $dsids_raw = explode(' ', trim($dsids_raw));
            $dsids = array();

            foreach ($dsids_raw as $dsid) {
              if(!empty($dsid)) {
                $dsids[] = $dsid;
              }
            }

            $dsids = implode(' ', $dsids);
            if(!empty($dsids)) {
              $fields = array(
                'content_model_name' => $content_model,
                'content_model_datastreams' => $dsids,
              );

              $content_model_id = db_insert('islandora_utils_plugin_validate_object_content_models')
                ->fields($fields)
                ->execute();
            }
          }
        }
      }

      $rows = array();
      $results = db_query('SELECT content_model_id, content_model_name, content_model_datastreams FROM {islandora_utils_plugin_validate_object_content_models}');
      foreach($results as $row) {
       $rows[$row->content_model_id] = array($row->content_model_name, $row->content_model_datastreams);
      }

      $form['islandora_utils_plugin_options']['islandora_utils_validate_object_settings']['islandora_utils_validate_object_settings_content_models'] = array(
        '#type' => 'tableselect',
        '#header' => array(t('Content Model'), t('Datastreams'),),
        '#options' => $rows,
        '#empty' => t('No members available.'),
      );


      $form['islandora_utils_plugin_options']['islandora_utils_validate_object_settings']['islandora_utils_validate_object_settings_content_models_name'] = array(
        '#type' => 'textfield',
         '#title' => t('Content Model'),
         '#default_value' => '',
      );

      $form['islandora_utils_plugin_options']['islandora_utils_validate_object_settings']['islandora_utils_validate_object_settings_content_models_ds'] = array(
        '#type' => 'textfield',
         '#title' => t('Datastreams'),
         '#default_value' => '',
         '#description' => t('Space seperated list of DSIDs. Use -DSID to ingore a DSID from the content model'),
      );

      $form['islandora_utils_plugin_options']['islandora_utils_validate_object_settings']['add_content_model'] = array(
        '#type' => 'button',
        '#value' => t('Add Content Model'),
        '#button_id' => 'islandora-utils-settings-validate-add-content-model',
        '#ajax' => array(
          'event' => 'click',
          'callback' => 'islandora_utils_validate_object_settings_add_content_model',
          'wrapper' => 'islandora-utils-settings-form',
          'method' => 'replace',
        ),
      );

       $form['islandora_utils_plugin_options']['islandora_utils_validate_object_settings']['islandora_utils_validate_object_settings_datastream_ids_merge'] = array(
         '#type' => 'checkbox',
          '#title' => t('Merge datastream ids with requirments from object content models'),
          '#default_value' => variable_get('islandora_utils_validate_object_settings_datastream_ids_merge', ''),
          '#description' => t('Checking this will validate against all DS ids from the content model, with the addional ones mentioned above '),
       );

       $form['islandora_utils_plugin_options']['islandora_utils_validate_object_settings']['islandora_utils_validate_object_settings_datastream_size_zero'] = array(
         '#type' => 'checkbox',
          '#title' => t('Check for zero byte datastreams (-1)'),
          '#default_value' => variable_get('islandora_utils_validate_object_settings_datastream_size_zero', ''),
       );


    break;
  }

}

function islandora_utils_validate_object_settings_add_content_model($form, &$form_state) {

  return drupal_rebuild_form('islandora_utils_settings_form', $form_state, $form);
}