<?php

function islandora_utils_permission() {
  return array();
}

function islandora_utils_menu() {

  $items['admin/islandora/utils'] = array(
    'title' => 'Islandora Utils',
    'description' => 'Advanced admin functionality for Islandora',
    'page callback' => 'islandora_utils_admin_page',
    'page arguments' => array('home'),
    'access callback' => TRUE,
  );

  $items['admin/islandora/utils/home'] = array(
    'title' => 'Home',
    'description' => 'Islandora Utility settings',
    'page callback' => 'islandora_utils_admin_page',
    'page arguments' => array('home'),
    'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/islandora/utils/settings'] = array(
    'title' => 'Settings',
    'description' => 'Islandora Utility settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_utils_settings_form'),
    'access callback' => TRUE,
    'file' => 'admin/islandora_utils.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function islandora_utils_admin_page($tab = '') {
  switch ($tab) {
    case 'home' :
    default :
      $output = drupal_get_form('islandora_utils_form');
  }
  return $output;
}

function islandora_utils_form($form, &$form_state) {
  $form = array();

  $form['islandora_utils_query'] = array(
    '#type' => 'fieldset',
    '#title' => t('RI Query'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    );

  $form['islandora_utils_query']['islandora_utils_query_query'] = array(
    '#type' => 'textarea',
    '#title' => t('Query'),
    '#default_value' => 'select $object from <#ri>
     where
     $object <fedora-model:state> <info:fedora/fedora-system:def/model#Active>
     and $object <fedora-model:hasModel> <info:fedora/islandora:pageCModel>
     order by $object',
    //
    );

  $form['islandora_utils_query']['islandora_utils_query_history'] = array(
    '#type' => 'item',
    '#markup' => t('save query history to db'),
    );

  $form['islandora_utils_pids'] = array(
    '#type' => 'textarea',
    '#title' => t('List of pids'),
    '#description' => t('space seperated list of pids'),
    '#default_value' => 'islandora:299',
    );

  $form['islandora_utils_plugins'] = array(
    '#type' => 'fieldset',
    '#title' => t('Plugins'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    );

  $plugins = module_invoke_all('islandora_utils_plugin');
  $form_state['storage']['plugins'] = $plugins;

  /**
   *
   * @todo make this re-arrangable for doing a order of operatations on a object
   */
  foreach($plugins as $plugin => $details) {
    $form['islandora_utils_plugins']["plugin-$plugin"] = array(
      '#type' => 'checkbox',
      '#title' => t($details['title']),
      '#description' => t($details['description']),
    );
  }

  $form['islandora_utils_plugin_options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Plugin options'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
    '#weight' => 10000,
  );

  return $form;
}


function islandora_utils_form_submit($form, &$form_state) {
  module_load_include('inc', 'islandora', 'includes/tuque');
  module_load_include('inc', 'islandora', 'includes/utilities');

  $batch = array(
    'title' => t('Process Batch'),
    'operations' => array(),
    'finished' => 'islandora_utils_process_complete',
  );


  $batch['operations'][] = array('islandora_utils_getpids', array($form_state));
  $batch['operations'][] = array('islandora_utils_process_objects', array($form_state));

  //foreach ($pids as $pid) {
    //$batch['operations'][] = array('islandora_utils_bob2', $pid);
  //}
  //$batch['operations'][] = array('islandora_utils_bob2', $form_state);

  //$batch['operations'][] = array('islandora_utils_process_objects', $form_state);

  batch_set($batch);
  //return $form;
}

function islandora_utils_bob2($pid, &$context) {
  dsm($pid, 'pid');
}

function islandora_utils_getpids($form_state, &$context) {
  module_load_include('inc', 'islandora', 'includes/tuque');
  module_load_include('inc', 'islandora', 'includes/utilities');

  $context['message'] = "Compiling PIDS";
  $pids = array();
  $values = $form_state['values'];

  $objects = array();

  if (!empty($values['islandora_utils_query_query'])) {
    try {
      $query = $values['islandora_utils_query_query'];
      $fedora = new IslandoraTuque();
      $objects = $fedora->repository->ri->itqlQuery($query, 'unlimited', '0'); // for itql
    } catch (Exception $e) {
      drupal_set_message(t('Your ITQL query is invalid.'), 'error');
    }

    if(count($objects) > 0) {
      foreach($objects as $object) {
        $pid = $object['object']['value'];
        $pids[$pid] = $pid;
      }
    }

  }

  $pids_raw = explode(' ', $values['islandora_utils_pids']);

  foreach ($pids_raw as $pid) {
    if(islandora_is_valid_pid($pid)) {
      $pids[$pid] = $pid;
    }
  }
  dsm($context, 'context');
  $context['results']['pids'] = $pids;
  foreach ($pids as $pid) {

  }

}

function islandora_utils_process_objects($form_state, &$context) {
  module_load_include('inc', 'islandora', 'includes/IslandoraTuque');
  module_load_include('inc', 'islandora', 'includes/utilities');

  $context['message'] = "Processing PIDS";
  $pids = $context['results']['pids'];
  dsm($pids, 'pidsss');
  $results = array();
  dsm($context, 'bbbbbbb');
  $plugins_raw = $form_state['storage']['plugins'];
  $plugins = array();

  foreach($plugins_raw as $plugin => $details) {
    if($form_state['values']["plugin-$plugin"]) {
      if($details['module'] && $details['file']) {
        $path = drupal_get_path('module', $details['module']) . '/' . $details['file'];
        if(is_readable($path)) {
          require_once($path);
          $plugin_class = $details['class'];
          $plugin_function = $details['function'];

          if (class_exists($plugin_class)) {
            $implementation = new $plugin_class();

            if(method_exists($implementation, $plugin_function)) {
              $plugins[$plugin] = $details;
              unset($implementation);
            }
            else {
              dsm('func is missing');
            }
          }
          else {
              dsm('class is missing');
          }
        }
        else {
          dsm('file is not readable');
        }
      }
    }
  }

  if(!isset($context['sandbox']['max'])) {
    $context['sandbox']['max'] = 0;
  }

  if(!isset($context['sandbox']['progress'])) {
    $context['sandbox']['progress'] = 0;
  }


  //add drupal batch here
  foreach($plugins as $plugin) {
    dsm($context['sandbox']['max'], 'max');
    $context['sandbox']['max'] += count($pids);

    foreach($pids as $pid) {
      $context['sandbox']['progress']++;

      $result = islandora_utils_process_object($pid, $plugin, $form_state);

      if(!isset($context['results']['results'])) {
        $context['results']['results'] = array();
      }

      $context['results']['results'] = array_merge($context['results']['results'], $result);
      $context['message'] = "Running " . $plugin['plugin_class'] ."=>". $plugin['plugin_function'];
    }
  }
}

function islandora_utils_process_object($pid, $plugin, $form_state) {

  $plugin_class = $plugin['class'];
  $plugin_function = $plugin['function'];

  $path = drupal_get_path('module', $plugin['module']) . '/' . $plugin['file'];
  require_once($path);

  $implementation = new $plugin_class($pid, $form_state);
  $implementation->$plugin_function();

  return $implementation->get_results();
}

function islandora_utils_process_complete($success, $results, $operations) {
  dsm($results,'complete function');
  islandora_utils_write_result($results['results']);
}

/**
 *
 * @param type $results
 *  array (
 *    array(
 *      type(status/error)
 *      pid
 *      message
 *    )
 * )
 */
function islandora_utils_write_result($results = array()) {
  global $base_url;
  //drupal_get_messages('status');
  //drupal_get_messages('error');
  if(count($results) > 0) {
    if(variable_get('islandora_utils_output_settings_sort', '')) {
      foreach ($results as $key => $row) {
        $results_sorted[$key]  = $row['type'];
      }
      $results_sorted = array_map('strtolower', $results_sorted);
      array_multisort($results_sorted, SORT_ASC, $results);
    }


    if(variable_get('islandora_utils_output_settings_output_file', '')) {
      $file_name = 'islandora_utils_'.date('Y-m-d-h:i:s').'.txt';
      $file_dir = variable_get('file_public_path', file_directory_temp());
      $results_file = file_create_filename($file_name, $file_dir);
      $fp = fopen($results_file, 'w');
    }
    foreach($results as $result) {
      if($result['type'] == 'status' && !variable_get('islandora_utils_output_settings_output_everything', '')) {
        continue;
      }

      if(variable_get('islandora_utils_output_settings_output_screen', '')) {
        drupal_set_message('<pre>'.$result['type'] . "\t" . $result['pid'] . "\t" . $result['message'].'</pre>', 'status');
      }
      if(variable_get('islandora_utils_output_settings_output_file', '')) {
        $text = $result['type'] . "\t" . $result['pid'] . "\t" . $result['message'];
        fwrite($fp, $text."\r");
      }
    }

    if(variable_get('islandora_utils_output_settings_output_file', '')) {
      fclose($fp);
      drupal_set_message(t('View results here >> '.l('View', $base_url.'/'.$results_file)));
    }
  }
  else {
    drupal_set_message(t('No resultsssss'));
  }

}

function islandora_utils_clean_result_files() {
  //foreach file in drupal file dir that starts with islandora_utilites - unlink
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_utils_newspapers_issueCModel_islandora_view_object($object, $page_number, $page_size) {
  dsm($object->id,'object');
  $viewer_url = variable_get('islandora_base_url', '') . '/get/' . $object->id . '/islandora:viewerSdef/getViewer';
  $output = '<iframe src="' . $viewer_url . '" frameborder="0" style="width: 100%; height: 800px;">Errors: unable to load viewer</iframe>';

  return $output;
}