<?php

function islandora_utils_plugin_export_islandora_utils_plugin() {
  return array(
    'export' => array (
      'title' => 'Export object',
      'module' => 'islandora_utils_plugin_export',
      'file' => 'ExportObjectPlugin.inc',
      'class' => 'ExportObjectPlugin',
      'function' => "process",
      'description' => 'Sync objects between 2 fedora and download objects locally',
    ),
  );
}


function islandora_utils_plugin_export_form_alter(&$form, &$form_state, $form_id) {
  dsm($form_id,'form id');
  switch ($form_id) {
    case 'islandora_utils_settings_form':
    case 'islandora_utils_form':
      $form['islandora_utils_plugin_options']['islandora_utils_plugin_export'] = array(
        '#type' => 'fieldset',
        '#title' => t('Plugin Export Options'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
      );

      $form['islandora_utils_plugin_options']['islandora_utils_plugin_export']['islandora_utils_plugin_export_download'] = array(
        '#type' => 'checkbox',
        '#title' => t('Download object'),
        '#default_value' => variable_get('islandora_utils_plugin_export_download', ''),
      );

      $form['islandora_utils_plugin_options']['islandora_utils_plugin_export']['islandora_utils_plugin_export_download_version'] = array(
        '#type' => 'checkbox',
        '#title' => t('Download object -- all versions'),
        '#default_value' => variable_get('islandora_utils_plugin_export_download_version', ''),
      );

      $form['islandora_utils_plugin_options']['islandora_utils_plugin_export']['islandora_utils_plugin_export_ingest_remote'] = array(
        '#type' => 'checkbox',
        '#title' => t('Local object to remote islandora'),
        '#default_value' => variable_get('islandora_utils_plugin_export_ingest_remote', ''),
      );

      $form['islandora_utils_plugin_options']['islandora_utils_plugin_export']['islandora_utils_plugin_export_ingest_local'] = array(
        '#type' => 'checkbox',
        '#title' => t('Remote object to local islandora'),
        '#default_value' => variable_get('islandora_utils_plugin_export_ingest_local', ''),
      );
    break;
  }

}